version: '3.8'

services:
  db:
    image: mysql:8.0.30
    environment:
      - MYSQL_USER=ng_lu
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ng_lu
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: "--character-set-server=utf8mb4 --max-connections=100000 --sql-mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
